export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_NEW_USER = " CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_ERROR = "GET_ERROR";
